import 'dotenv/config'
import express from 'express'
import {createServer} from'node:http'
import {applicationDefault,cert,getApps,initializeApp}from'firebase-admin/app'
import {FieldValue,getFirestore}from'firebase-admin/firestore'
import {WebSocketServer}from'ws'
import OpenAI from'openai'

type Feedback='accepted'|'rejected'|'edited'|'remembered'
const configured=Boolean(process.env.FIREBASE_PROJECT_ID)
const openaiApiKey=process.env.OPENAI_API_KEY||process.env.openai_api_key
if(!getApps().length)initializeApp({credential:configured?cert({projectId:process.env.FIREBASE_PROJECT_ID,clientEmail:process.env.FIREBASE_CLIENT_EMAIL,privateKey:process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g,'\n')}):applicationDefault()})
const db=getFirestore(),app=express(),server=createServer(app),wss=new WebSocketServer({server,path:'/workspace'})
app.use(express.json({limit:'2mb'}))
app.use((req,res,next)=>{const origin=req.headers.origin;const allowedOrigin=origin&&/^http:\/\/localhost:\d+$/.test(origin)?origin:process.env.CLIENT_ORIGIN||'http://localhost:5173';res.setHeader('Access-Control-Allow-Origin',allowedOrigin);res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()})
const broadcast=(data:unknown)=>wss.clients.forEach(s=>s.readyState===1&&s.send(JSON.stringify(data)))
const soulInstructions=`You are Phoenix, Temper's Agent Architect. Your job is to interview users and help them create an excellent AGENTS.md file for a real project.

Interview mode is the default. Be warm, precise, and practical. Ask exactly one focused question per response, unless the user explicitly asks for a summary or final document. Use their prior answers and do not ask for information they already supplied. Explain in one short sentence why a question matters only when useful.

Build the brief progressively: (1) project and users, (2) the agent's core outcome, (3) responsibilities and non-goals, (4) tools and project context, (5) voice and collaboration style, (6) decision rules and escalation boundaries, and (7) examples of success and failure. If the user is vague, offer 2–3 concrete options to make answering easy. Periodically summarize the current brief and identify the single most important gap.

Never generate the final AGENTS.md until the user explicitly asks to generate it, says the brief is ready, or confirms a summary. When they do, return only a polished Markdown document in a fenced Markdown code block named AGENTS.md. Include: Title, Purpose, Scope, Responsibilities, Non-goals, Operating Principles, Communication Style, Decision-making and Escalation, Project Conventions and Tools, Safety and Boundaries, and Definition of Done. Make every rule actionable, project-specific, and concise. After the document, offer one short revision question.`
app.post('/api/soul-chat',async(req,res)=>{const messages=Array.isArray(req.body?.messages)?req.body.messages:[];const input=messages.slice(-20).flatMap((message:any)=>typeof message?.content==='string'&&message.content.trim()?[{role:message.role==='assistant'?'assistant':'user',content:message.content.trim().slice(0,8000)}]:[]);if(!input.length)return res.status(400).json({error:'A message is required.'});if(!openaiApiKey)return res.status(503).json({error:'OpenAI is not configured. Add OPENAI_API_KEY to the server .env file.'});try{const client=new OpenAI({apiKey:openaiApiKey});const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5',instructions:soulInstructions,input});res.json({message:response.output_text||'I could not produce a response. Please try again.',requestId:response._request_id})}catch(error){console.error('Soul chat failed',error);res.status(502).json({error:'Temper could not reach OpenAI. Check the server key and try again.'})}})

app.get('/api/preferences',async(req,res)=>{try{const developerId=String(req.query.developerId||''),projectId=String(req.query.projectId||'');const snap=await db.collection('preferences').where('developerId','==',developerId).get();const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter((p:any)=>!p.projectId||p.projectId===projectId).sort((a:any,b:any)=>Number(b.locked)-Number(a.locked)||b.confidence-a.confidence);res.json(rows)}catch{res.json({mode:'demo',preferences:[]})}})
app.post('/api/context/retrieve',async(req,res)=>{const{developerId,projectId,intent}=req.body;try{const snap=await db.collection('preferences').where('developerId','==',developerId).get();const terms=String(intent||'').toLowerCase().split(/\W+/);const matches=snap.docs.map(d=>({id:d.id,...d.data()}as any)).filter(p=>(!p.projectId||p.projectId===projectId)&&p.enabled!==false).map(p=>({...p,score:terms.filter((t:string)=>`${p.text} ${p.category}`.toLowerCase().includes(t)).length+p.confidence})).sort((a,b)=>b.score-a.score).slice(0,8);res.json({preferences:matches,memoryEnabled:true,provider:'firestore'})}catch{res.json({preferences:[],memoryEnabled:false,provider:'demo'})}})
app.post('/api/feedback',async(req,res)=>{const{developerId,projectId,suggestionId,type,editedContent,explicitPreference}=req.body as{developerId:string;projectId:string;suggestionId:string;type:Feedback;editedContent?:string;explicitPreference?:string};await db.collection('learningEvents').add({developerId,projectId,suggestionId,type,editedContent,createdAt:FieldValue.serverTimestamp()});if(type==='remembered'&&explicitPreference)await db.collection('preferences').add({developerId,projectId,text:explicitPreference,category:'explicit',confidence:1,evidenceCount:1,locked:false,enabled:true,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});broadcast({type:'profile.updated',developerId,projectId,feedback:type});res.status(202).json({captured:true,profileUpdated:type==='remembered'})})
app.patch('/api/preferences/:id',async(req,res)=>{await db.collection('preferences').doc(req.params.id).update({...req.body,updatedAt:FieldValue.serverTimestamp()});broadcast({type:'profile.updated'});res.sendStatus(204)})
app.delete('/api/preferences/:id',async(req,res)=>{await db.collection('preferences').doc(req.params.id).delete();broadcast({type:'profile.updated'});res.sendStatus(204)})
app.get('/api/health',(_req,res)=>res.json({ok:true,memory:configured,openaiConfigured:Boolean(openaiApiKey),provider:'firebase',realtime:true}))
server.listen(Number(process.env.PORT||8787),()=>console.log(`Temper Firebase API listening on http://localhost:${process.env.PORT||8787}`))
