import React,{useMemo,useState} from'react'
import{createRoot}from'react-dom/client'
import{Brain,Check,ChevronDown,CircleUserRound,Code2,Database,Eye,Files,GitBranch,History,Lock,MessageSquareText,PanelLeftClose,Pencil,Play,Plus,RotateCcw,Search,Send,Settings2,Shield,Sparkles,TerminalSquare,ThumbsDown,Trash2,X,Zap}from'lucide-react'
import'./styles.css'
import'./extras.css'

type Pref={id:number;name:string;value:string;scope:'Global'|'Project';confidence:number;locked?:boolean;source:string}
type Message={id:number;role:'user'|'assistant';text:string;status?:'accepted'|'rejected'|'edited'}
const seed:Pref[]=[
 {id:1,name:'TypeScript first',value:'Always',scope:'Global',confidence:98,locked:true,source:'12 accepted changes'},
 {id:2,name:'Functional components',value:'Strong',scope:'Global',confidence:94,source:'8 accepted changes'},
 {id:3,name:'Compact explanations',value:'Preferred',scope:'Global',confidence:89,source:'Conversation style'},
 {id:4,name:'Tests alongside changes',value:'Usually',scope:'Project',confidence:84,source:'5 edited suggestions'},
 {id:5,name:'Early returns',value:'Prefer',scope:'Project',confidence:91,locked:true,source:'Explicitly remembered'},
 {id:6,name:'Named exports',value:'Shared utilities',scope:'Global',confidence:77,source:'Code edit pattern'},
]
const source=`import { useState, useEffect } from 'react';

type User = {
  id: string;
  name: string;
  role: string;
};

export default function UserList() {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/users')
      .then((res) => res.json())
      .then((data) => {
        setUsers(data);
        setLoading(false);
      });
  }, []);

  if (loading) return <Spinner />;

  return (
    <div className="user-list">
      {users.map((user) => (
        <UserCard key={user.id} user={user} />
      ))}
    </div>
  );
}`

function App(){
 const[tab,setTab]=useState<'chat'|'context'>('chat'),[prompt,setPrompt]=useState(''),[memory,setMemory]=useState(true),[dashboard,setDashboard]=useState(false),[prefs,setPrefs]=useState(seed),[scope,setScope]=useState<'All'|'Global'|'Project'>('All'),[toast,setToast]=useState('')
 const[messages,setMessages]=useState<Message[]>([{id:1,role:'user',text:'Can you refactor this component to handle errors and add a retry?'},{id:2,role:'assistant',text:'I’ll add typed error state and a retry handler, keeping the component functional and avoiding unnecessary abstraction.'}])
 const visible=useMemo(()=>prefs.filter(p=>scope==='All'||p.scope===scope),[prefs,scope])
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)}
 const send=()=>{if(!prompt.trim())return;const n=Date.now();setMessages(m=>[...m,{id:n,role:'user',text:prompt.trim()},{id:n+1,role:'assistant',text:memory?'I’ll keep this TypeScript-first, follow the existing functional style, and include a focused test.':'I’ll use only the current conversation and codebase context because project memory is off.'}]);setPrompt('')}
 const feedback=(id:number,status:'accepted'|'rejected'|'edited')=>{setMessages(m=>m.map(x=>x.id===id?{...x,status}:x));notify(status==='accepted'?'Accepted — preference evidence strengthened':status==='edited'?'Edit captured as a learning signal':'Rejected — no preference saved yet')}
 return <main className="app-shell"><header><div className="brand"><div className="brandmark"><Code2 size={17}/></div><span>temper</span><em>/</em><small>workspace</small></div><button className="project"><span className="status-dot"/>acme/dashboard <ChevronDown size={14}/></button><div className="header-actions"><button className="icon-btn"><Search size={17}/></button><button className="branch"><GitBranch size={15}/>main<ChevronDown size={13}/></button><button className="avatar" onClick={()=>setDashboard(true)}>AR</button></div></header>
 <section className="workspace"><aside className="rail"><button className="active"><Files size={20}/></button><button><Search size={20}/></button><button><GitBranch size={20}/></button><button onClick={()=>setDashboard(true)}><Brain size={20}/></button><div className="rail-bottom"><button onClick={()=>setDashboard(true)}><Settings2 size={20}/></button><button><CircleUserRound size={20}/></button></div></aside>
 <aside className="memory-panel"><div className="panel-heading"><span>YOUR WORKSPACE</span><PanelLeftClose size={15}/></div><div className="profile-card"><div className="profile-top"><div className="brain-icon"><Brain size={18}/></div><div><h3>Developer fingerprint</h3><p>{memory?'Continuously learning':'Paused for this project'}</p></div><button className={'toggle '+(memory?'on':'')} onClick={()=>{setMemory(!memory);notify(memory?'Memory disabled for this project':'Memory enabled')}}><span/></button></div><div className="learned"><Sparkles size={13}/>{prefs.length} active preferences · 24 signals</div></div><div className="section-title"><span>BUILD PREFERENCES</span><button onClick={()=>setDashboard(true)}>View all</button></div><div className="preferences">{prefs.slice(0,4).map(p=><div className="pref" key={p.id}><span>{p.name}</span><em>{p.value}</em></div>)}</div><div className="section-title"><span>RECENTLY LEARNED</span></div><div className="learn-item"><div className="learn-icon"><Zap size={14}/></div><div><p>You prefer early returns over nested conditionals.</p><small>2 min ago · This workspace</small></div></div><div className="learn-item"><div className="learn-icon purple"><Code2 size={14}/></div><div><p>Use named exports for shared utilities.</p><small>Yesterday · api-service</small></div></div><button className="memory-footer" onClick={()=>setDashboard(true)}><History size={14}/>Memory dashboard<span>→</span></button></aside>
 <section className="editor-area"><div className="tabs"><div className="file-tab active"><span className="react-icon">⚛</span>UserList.tsx<X size={13}/></div><div className="file-tab"><span className="ts-icon">TS</span>api.ts<span className="dirty"/></div><button><Plus size={15}/></button><div className="editor-actions"><Play size={15}/><span>Run</span><ChevronDown size={13}/></div></div><div className="breadcrumbs"><span>src</span><b>›</b><span>components</span><b>›</b><span className="react-icon">⚛</span><span>UserList.tsx</span><b>›</b><span>□ UserList</span></div><div className="code-wrap"><div className="code-lines">{source.split('\n').map((line,i)=><div className="code-row" key={i}><span className="line-no">{i+1}</span><code>{line||' '}</code></div>)}</div><div className="minimap"/></div><div className="statusbar"><div><GitBranch size={12}/>main*</div><div><X size={12}/>0 <span className="warn">△</span>1</div><div className="status-right"><span>Ln 14, Col 18</span><span>Spaces: 2</span><span>UTF-8</span><span>{'{ }'} TypeScript React</span></div></div></section>
 <aside className="assistant-panel"><div className="assistant-tabs"><button className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}><MessageSquareText size={15}/>Assistant</button><button className={tab==='context'?'active':''} onClick={()=>setTab('context')}>Context <span>4</span></button><button className="more">•••</button></div>{tab==='chat'?<><div className="assistant-body"><div className="ai-heading"><div className="ai-logo"><Sparkles size={17}/></div><div><h3>Temper</h3><p><span className={memory?'':'off'}/>{memory?'Your preferences are active':'Project memory is off'}</p></div></div><div className={'retrieval '+(!memory?'disabled':'')}><div className="retrieval-title"><Brain size={14}/><b>{memory?'Retrieved your build style':'Preference retrieval paused'}</b><span>{memory?'4 signals':'0 signals'}</span></div>{memory&&<><div className="chips"><span>TypeScript</span><span>Functional</span><span>Concise</span><span>Tests</span></div><p><Eye size={11}/> These preferences will influence this response.</p></>}</div>{messages.map(m=>m.role==='user'?<div className="user-message" key={m.id}>{m.text}</div>:<div className="assistant-message" key={m.id}><div className="mini-ai"><Sparkles size={12}/></div><div><p>{m.text}</p>{m.id===2&&<div className="change-card"><div><span className="react-icon">⚛</span><b>UserList.tsx</b><em>+18 −4</em></div><p><span>+</span>Typed error state</p><p><span>+</span>Retry with the same fetch function</p><p><span>+</span>Early return for error UI</p><button onClick={()=>feedback(m.id,'accepted')}>{m.status==='accepted'?<><Check size={12}/>Applied</>:<>Apply changes <kbd>⌘ ↵</kbd></>}</button></div>}<div className="feedback"><span>Was this your style?</span><button className={m.status==='accepted'?'selected':''} onClick={()=>feedback(m.id,'accepted')}><Check size={11}/>Accept</button><button className={m.status==='edited'?'selected':''} onClick={()=>feedback(m.id,'edited')}><Pencil size={11}/>Edit</button><button className={m.status==='rejected'?'selected':''} onClick={()=>feedback(m.id,'rejected')}><ThumbsDown size={11}/>Reject</button><button onClick={()=>notify('Saved as an explicit preference')}><Brain size={11}/>Remember this</button></div></div></div>)}</div><div className="composer"><div className="composer-box"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask Temper anything…"/><div className="composer-tools"><div><button><Plus size={16}/></button><button><b>@</b></button><span className="model">Personalized model <ChevronDown size={12}/></span></div><button className="send" onClick={send}><Send size={14}/></button></div></div><p><Sparkles size={11}/>Preferences retrieved before every response</p></div></>:<Context memory={memory}/>}</aside></section>
 {dashboard&&<div className="modal-backdrop" onMouseDown={()=>setDashboard(false)}><section className="dashboard" onMouseDown={e=>e.stopPropagation()}><div className="dashboard-head"><div><span className="eyebrow">DEVELOPER MEMORY</span><h2>Your developer fingerprint</h2><p>Inspect and control what Temper has learned about how you build.</p></div><button className="modal-close" onClick={()=>setDashboard(false)}><X size={18}/></button></div><div className="stats"><div><Brain/><span><b>{prefs.length}</b>Preferences</span></div><div><Database/><span><b>24</b>Evidence signals</span></div><div><Shield/><span><b>2</b>Locked by you</span></div><div><Zap/><span><b>91%</b>Profile confidence</span></div></div><div className="dashboard-toolbar"><div>{(['All','Global','Project']as const).map(s=><button key={s} className={scope===s?'active':''} onClick={()=>setScope(s)}>{s}{s==='Project'?' · acme/dashboard':''}</button>)}</div><button className="memory-master" onClick={()=>setMemory(!memory)}><span className={'status-dot '+(!memory?'paused':'')}/>{memory?'Memory on for project':'Memory off for project'}</button></div><div className="preference-table"><div className="table-head"><span>Preference</span><span>Scope</span><span>Confidence</span><span>Evidence</span><span>Controls</span></div>{visible.map(p=><div className="table-row" key={p.id}><div><b>{p.name}</b><small>{p.value}</small></div><span className={'scope '+p.scope.toLowerCase()}>{p.scope}</span><div className="confidence"><span><i style={{width:p.confidence+'%'}}/></span><small>{p.confidence}%</small></div><span className="evidence">{p.source}</span><div className="row-actions"><button><Pencil size={14}/></button><button className={p.locked?'locked':''} onClick={()=>setPrefs(a=>a.map(x=>x.id===p.id?{...x,locked:!x.locked}:x))}><Lock size={14}/></button><button onClick={()=>setPrefs(a=>a.filter(x=>x.id!==p.id))}><Trash2 size={14}/></button></div></div>)}</div><div className="privacy-note"><Shield size={17}/><div><b>Learning requires strong evidence</b><p>Profiles update only after repeated behavior or explicit confirmation. Rejections alone never become preferences.</p></div><button><RotateCcw size={14}/>Export memory</button></div></section></div>}{toast&&<div className="toast"><Check size={14}/>{toast}</div>}</main>
}
function Context({memory}:{memory:boolean}){return <div className="context-panel"><div className="context-title"><h3>Response context</h3><p>Live inputs assembled before the next response.</p></div>{[['Developer request','Current prompt + conversation intent'],['Preference retrieval',memory?'4 semantic matches from Atlas':'Disabled for this project'],['Project context','UserList.tsx · api.ts · package.json'],['Conversation history','6,842 weighted tokens']].map((x,i)=><React.Fragment key={x[0]}>{i>0&&<div className="pipeline-line"/>}<div className={'pipeline-step '+(i===1&&!memory?'muted':'active')}><span>{i+1}</span><div><b>{x[0]}</b><small>{x[1]}</small></div>{i===1&&!memory?<Lock size={14}/>:<Check size={14}/>}</div></React.Fragment>)}<div className="context-card"><div><TerminalSquare size={15}/><b>Codebase index</b><span>Synced</span></div><p>142 files · 2,481 symbols · updated just now</p></div><div className="context-card"><div><Database size={15}/><b>Vector memory</b><span>{memory?'Connected':'Paused'}</span></div><p>MongoDB Atlas · cosine similarity · project filtered</p></div></div>}
createRoot(document.getElementById('root')!).render(<App/>)
