import { signOut, type User } from "firebase/auth";
import { BrainCircuit, Check, Code2, Flame, LogOut, MessageSquareCode, Plus, Settings, Sparkles } from "lucide-react";
import { auth } from "./firebase";

export function Panel({ user }: { user: User }) {
  const name = user.displayName || user.email?.split("@")[0] || "Builder";
  return <div className="panel-shell"><aside className="panel-sidebar"><div className="panel-brand"><span className="brand-mark"><Flame size={18}/></span> temper<span>.</span></div><nav><button className="active"><Sparkles/> Overview</button><button><BrainCircuit/> Memory</button><button><MessageSquareCode/> Sessions</button><button><Settings/> Settings</button></nav><div className="panel-user"><span>{name.slice(0,2).toUpperCase()}</span><div><b>{name}</b><small>{user.email}</small></div><button onClick={()=>auth && signOut(auth)} aria-label="Sign out"><LogOut/></button></div></aside>
    <main className="panel-main"><header className="panel-header"><div><p>WORKSPACE</p><h1>Good to see you, {name.split(" ")[0]}.</h1></div><button><Plus/> New session</button></header><section className="panel-stats"><article><span><BrainCircuit/></span><div><b>6</b><small>Learned preferences</small></div></article><article><span><Check/></span><div><b>24</b><small>Accepted patterns</small></div></article><article><span><Code2/></span><div><b>3</b><small>Connected projects</small></div></article></section>
      <section className="panel-grid"><article className="panel-card preferences-card"><div className="panel-card-head"><div><p>YOUR MEMORY</p><h2>Active preferences</h2></div><button>View all</button></div>{[["TypeScript first","Always","98%"],["Functional components","Strong","94%"],["Compact explanations","Preferred","89%"],["Tests alongside changes","Usually","84%"]].map(([a,b,c])=><div className="panel-pref" key={a}><span className="panel-check"><Check/></span><div><b>{a}</b><small>{b}</small></div><div className="confidence"><i style={{width:c}}/></div><em>{c}</em></div>)}</article>
      <article className="panel-card activity-card"><div className="panel-card-head"><div><p>RECENT ACTIVITY</p><h2>Latest signals</h2></div></div><div className="activity"><span><Check/></span><div><b>Early returns accepted</b><small>acme / web-app · 12 min ago</small></div></div><div className="activity"><span><BrainCircuit/></span><div><b>Preference strengthened</b><small>TypeScript first · Yesterday</small></div></div><div className="activity"><span><Code2/></span><div><b>Project connected</b><small>design-system · 3 days ago</small></div></div></article></section>
    </main></div>;
}
