import { useState, type ComponentType } from "react";
import { signOut, type User } from "firebase/auth";
import { Archive, BrainCircuit, Check, ChevronRight, Code2, Flame, Globe2, Lock, LogOut, MessageSquareCode, MoreHorizontal, Palette, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, UserRound } from "lucide-react";
import { auth } from "./firebase";
import poseNeutral from "../assets/01_neutral-removebg-preview.png";
import poseInspiring from "../assets/02_inspiring.png";
import poseFocused from "../assets/03_focused-removebg-preview.png";
import poseConfident from "../assets/04_confident.png";
import poseCurious from "../assets/05_curious.png";
import poseThinking from "../assets/06_thinking-removebg-preview.png";
import poseExplaining from "../assets/07_explaining-removebg-preview.png";
import poseLearning from "../assets/08_learning-removebg-preview.png";
import poseExcited from "../assets/09_excited.png";
import poseResting from "../assets/10_resting-removebg-preview.png";

type Page = "overview" | "memory" | "sessions" | "personalizer" | "settings";
type Icon = ComponentType<{ size?: number }>;
const preferences = [
  {name:"TypeScript first",detail:"Prefer TypeScript for new files and examples",scope:"Global",confidence:98,evidence:"18 signals"},
  {name:"Functional components",detail:"Use hooks and functional React components",scope:"Global",confidence:94,evidence:"12 signals"},
  {name:"Compact explanations",detail:"Lead with the result and keep prose concise",scope:"Global",confidence:89,evidence:"9 signals"},
  {name:"Tests alongside changes",detail:"Add focused tests when behavior changes",scope:"Project",confidence:84,evidence:"7 signals"},
  {name:"Early returns",detail:"Reduce nesting with guard clauses",scope:"Project",confidence:78,evidence:"5 signals"},
];
const sessions = [
  {title:"Refactor authentication flow",project:"acme/web-app",time:"12 min ago",messages:18,status:"Active"},
  {title:"Add repository search filters",project:"temper/dashboard",time:"Yesterday",messages:31,status:"Complete"},
  {title:"Review payments webhook",project:"acme/api",time:"Aug 21",messages:14,status:"Complete"},
  {title:"Design onboarding state",project:"temper/dashboard",time:"Aug 19",messages:26,status:"Archived"},
];

function Heading({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy:string;action?:React.ReactNode}){return <header className="panel-page-heading"><div><p>{eyebrow}</p><h1>{title}</h1><span>{copy}</span></div>{action}</header>}
function Overview({name,go}:{name:string;go:(p:Page)=>void}){return <><Heading eyebrow="WORKSPACE" title={`Good to see you, ${name.split(" ")[0]}.`} copy="Here’s what Temper has learned from your recent work." action={<button className="panel-primary"><Plus/> New session</button>}/><section className="panel-stats"><article><span><BrainCircuit/></span><div><b>6</b><small>Learned preferences</small></div></article><article><span><Check/></span><div><b>24</b><small>Accepted patterns</small></div></article><article><span><Code2/></span><div><b>3</b><small>Connected projects</small></div></article></section><section className="panel-grid"><article className="panel-card"><div className="panel-card-head"><div><p>YOUR MEMORY</p><h2>Active preferences</h2></div><button onClick={()=>go("memory")}>View all</button></div>{preferences.slice(0,4).map(p=><div className="panel-pref" key={p.name}><span className="panel-check"><Check/></span><div><b>{p.name}</b><small>{p.scope}</small></div><div className="confidence"><i style={{width:`${p.confidence}%`}}/></div><em>{p.confidence}%</em></div>)}</article><article className="panel-card"><div className="panel-card-head"><div><p>RECENT ACTIVITY</p><h2>Latest signals</h2></div></div>{[[Check,"Early returns accepted","acme / web-app · 12 min ago"],[BrainCircuit,"Preference strengthened","TypeScript first · Yesterday"],[Code2,"Project connected","design-system · 3 days ago"]].map(([A,b,c])=>{const ActivityIcon=A as Icon;return <div className="activity" key={String(b)}><span><ActivityIcon/></span><div><b>{String(b)}</b><small>{String(c)}</small></div></div>})}</article></section></>}

function MemoryPage(){const[q,setQ]=useState("");const[enabled,setEnabled]=useState(true);const shown=preferences.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));return <><Heading eyebrow="MEMORY" title="What Temper knows." copy="Review learned preferences. You always control what stays." action={<button className="panel-primary"><Plus/> Add preference</button>}/><section className="memory-summary"><div><BrainCircuit/><span><b>{preferences.length} active memories</b><small>Applied automatically in every session</small></span></div><label><span>{enabled?"Memory on":"Memory paused"}</span><button className={`panel-toggle ${enabled?"on":""}`} onClick={()=>setEnabled(!enabled)}><i/></button></label></section><div className="panel-toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search memories…"/></label><button><SlidersHorizontal/> Filter</button></div><section className="memory-list"><div className="memory-list-head"><span>Preference</span><span>Scope</span><span>Confidence</span><span>Evidence</span><span/></div>{shown.map(p=><article key={p.name}><div><span className="memory-icon"><Check/></span><span><b>{p.name}</b><small>{p.detail}</small></span></div><em className={p.scope==="Project"?"project":""}>{p.scope}</em><div className="memory-confidence"><span><i style={{width:`${p.confidence}%`}}/></span><b>{p.confidence}%</b></div><small>{p.evidence}</small><button><MoreHorizontal/></button></article>)}</section><aside className="privacy-strip"><ShieldCheck/><div><b>Your memory is private and reversible.</b><small>Every preference can be edited or removed at any time.</small></div><button>Privacy controls <ChevronRight/></button></aside></>}

function SessionsPage(){const[filter,setFilter]=useState("All");const shown=filter==="All"?sessions:sessions.filter(s=>s.status===filter);return <><Heading eyebrow="SESSIONS" title="Your conversations." copy="Resume recent work or revisit earlier decisions." action={<button className="panel-primary"><Plus/> New session</button>}/><div className="session-controls"><div>{["All","Active","Complete","Archived"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><label><Search/><input placeholder="Search sessions…"/></label></div><section className="session-list">{shown.map((s,i)=><article key={s.title}><span className="session-icon">{i===0?<Sparkles/>:<MessageSquareCode/>}</span><div><b>{s.title}</b><small><Code2/> {s.project}</small></div><span className={`session-status ${s.status.toLowerCase()}`}>{s.status}</span><span className="session-meta">{s.messages} messages<small>{s.time}</small></span><button><ChevronRight/></button></article>)}</section></>}

const poses=[
  ["Neutral",poseNeutral],["Inspiring",poseInspiring],["Focused",poseFocused],["Confident",poseConfident],["Curious",poseCurious],
  ["Thinking",poseThinking],["Explaining",poseExplaining],["Learning",poseLearning],["Excited",poseExcited],["Resting",poseResting],
] as const;
function PersonalizerPage(){const[name,setName]=useState("Ember");const[pose,setPose]=useState(0);const[tone,setTone]=useState("Warm mentor");const[color,setColor]=useState("#ff6b32");return <><Heading eyebrow="MD PERSONALIZER" title="Create your own MD." copy="Shape a coding companion with its own name, voice, color, and expressions." action={<button className="panel-primary"><Sparkles/> Save MD</button>}/><section className="personalizer-shell" style={{"--md-color":color} as React.CSSProperties}><div className="pose-orbit"><div className="orbit-ring one"/><div className="orbit-ring two"/>{poses.map(([label,image],i)=><button key={label} className={`orbit-pose pose-${i} ${pose===i?"selected":""}`} onClick={()=>setPose(i)} title={label}><img src={image} alt={`${label} pose`}/><span>{label}</span></button>)}<div className="md-stage"><span className="stage-glow"/><img src={poses[pose][1]} alt={`${name}, ${poses[pose][0]} pose`}/><div><i/><span><b>{name}</b><small>{poses[pose][0]} mode</small></span></div></div></div><aside className="personalizer-controls"><div className="personalizer-kicker"><Palette/> CHARACTER STUDIO</div><h2>Make it feel like yours.</h2><p>These choices shape how your MD looks and communicates during a session.</p><label>MD name<input value={name} onChange={e=>setName(e.target.value)} maxLength={18}/></label><label>Personality<select value={tone} onChange={e=>setTone(e.target.value)}><option>Warm mentor</option><option>Direct builder</option><option>Curious partner</option><option>Careful reviewer</option><option>Energetic driver</option></select></label><label>Ember color<div className="color-options">{["#ff6b32","#a879ff","#ffb12b","#56cfa0","#5f9cff"].map(c=><button key={c} className={color===c?"active":""} style={{background:c}} onClick={()=>setColor(c)} aria-label={`Choose ${c}`}/>)}</div></label><div className="voice-preview"><span><MessageSquareCode/></span><div><b>{name} says</b><p>{tone==="Direct builder"?"I’ve made the change. Tests pass—ready for the next one.":tone==="Careful reviewer"?"Let’s verify the current behavior first, then make the smallest safe change.":"I’m ready. Let’s build something thoughtful together."}</p></div></div><button className="create-md"><Sparkles/> Create {name}</button></aside></section></>}

function SettingsPage({user}:{user:User}){const[signals,setSignals]=useState(true);const[projects,setProjects]=useState(true);return <><Heading eyebrow="SETTINGS" title="Make Temper yours." copy="Manage your profile, memory behavior, and connected tools."/><div className="settings-layout"><nav><button className="active"><UserRound/> Profile</button><button><BrainCircuit/> Memory</button><button><Globe2/> Integrations</button><button><Lock/> Privacy</button></nav><div className="settings-content"><section className="settings-card"><header><h2>Profile</h2><p>Your personal details and workspace identity.</p></header><div className="profile-editor"><span>{(user.displayName||"BU").slice(0,2).toUpperCase()}</span><div><b>{user.displayName||"Builder"}</b><small>{user.email}</small></div><button>Change avatar</button></div><div className="settings-fields"><label>Display name<input defaultValue={user.displayName||"Builder"}/></label><label>Email address<input defaultValue={user.email||""} disabled/></label></div><button className="save-settings">Save changes</button></section><section className="settings-card"><header><h2>Memory behavior</h2><p>Choose how Temper learns during your sessions.</p></header>{[["Learn from accepted suggestions","Strengthen preferences when you approve generated changes.",signals,()=>setSignals(!signals)],["Project-specific memory","Keep repository conventions separate from global preferences.",projects,()=>setProjects(!projects)]].map(([a,b,on,toggle])=><div className="setting-row" key={String(a)}><div><b>{String(a)}</b><small>{String(b)}</small></div><button className={`panel-toggle ${on?"on":""}`} onClick={toggle as ()=>void}><i/></button></div>)}</section><section className="settings-card danger-card"><header><h2>Data controls</h2><p>Export or permanently remove your Temper memory.</p></header><div className="danger-actions"><button><Archive/> Export my data</button><button><Trash2/> Delete all memory</button></div></section></div></div></>}

export function Panel({user}:{user:User}){const name=user.displayName||user.email?.split("@")[0]||"Builder";const[page,setPage]=useState<Page>("overview");const items:[Page,string,Icon][]=[["overview","Overview",Sparkles],["memory","Memory",BrainCircuit],["sessions","Sessions",MessageSquareCode],["personalizer","Personalizer",Palette],["settings","Settings",Settings]];return <div className="panel-shell"><aside className="panel-sidebar"><div className="panel-brand"><span className="brand-mark"><Flame size={18}/></span> temper<span>.</span></div><nav>{items.map(([id,label,NavIcon])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}><NavIcon/> {label}</button>)}</nav><div className="panel-user"><span>{name.slice(0,2).toUpperCase()}</span><div><b>{name}</b><small>{user.email}</small></div><button onClick={()=>auth&&signOut(auth)}><LogOut/></button></div></aside><main className="panel-main">{page==="overview"&&<Overview name={name} go={setPage}/>} {page==="memory"&&<MemoryPage/>} {page==="sessions"&&<SessionsPage/>} {page==="personalizer"&&<PersonalizerPage/>} {page==="settings"&&<SettingsPage user={user}/>}</main></div>}
